name: update-token

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # 每周日8点，Github 0点
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: leancloud Update token # leancloud
      env:
        # leancloud配置
        APPID: ${{ secrets.APPID }}
        APPKEY: ${{ secrets.APPKEY }}
        # 百度统计配置
        APIKEY: ${{ secrets.APIKEY }}
        SECRETKEY: ${{ secrets.SECRETKEY }}
      working-directory: ./Site_Analytics/baidu
      run: |
        python run.py

    - name: keep alive
      uses: gautamkrishnar/keepalive-workflow@master # keep workflows from being suspended when no commit for a long time